<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // auto-generated by Laravel
        // User::factory(10)->create();
        // User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        $this->call([
            AclSeeder::class,
            UsersTableSeeder::class,

            StatusesTableSeeder::class,
            DestinationsTableSeeder::class,
            WorkstationsTableSeeder::class,
        ]);
    }
}
