version: '3.8'
services:
  pipeq:
    build:
      target: production
      context: .
      dockerfile: Dockerfile

    image: pipeq:latest

    container_name: "${CONTAINER_NAME:-pipeq}"

    volumes:
      - "pipeq_database:/var/www/html/database"

    ports:
      - "80:80"
      - "8080:8080"
    
    restart: "unless-stopped"

volumes:
  pipeq_database:
    name: "${CONTAINER_NAME:-pipeq}_database"
