services:
  pipeq:
    build:
      target: production
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_IMAGE_NAME: ${DOCKER_IMAGE_NAME}
        CONTAINER_NAME: ${CONTAINER_NAME}
        HTTP_PORT: ${HTTP_PORT}
        REVERB_PORT: ${REVERB_PORT}

    image: "${DOCKER_IMAGE_NAME:-PipeQ}:latest"

    container_name: "${CONTAINER_NAME:-PipeQ}"

    volumes:
      - "pipeq_database:/var/www/html/database"

    ports:
      - "${HTTP_PORT}:80"
      - "${REVERB_PORT}:8080"
    
    environment:
      - DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}
      - CONTAINER_NAME=${CONTAINER_NAME}
      - HTTP_PORT=${HTTP_PORT}
      - REVERB_PORT=${REVERB_PORT}
    
    restart: "unless-stopped"

volumes:
  pipeq_database:
    name: "${CONTAINER_NAME:-pipeq}_database"
